## Config

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
DATA_DIR = Path() / "data" / "raw"

def load_file(file, sep=',', skiprows=0) -> pd.DataFrame:
    df = pd.read_csv(
        DATA_DIR / file, 
        sep=sep,
        low_memory=False,
        encoding='utf-8',
        skiprows=skiprows,
        na_values=['..', 'NA', 'N/A', '']
    ).dropna(how='all')

    show_info(df)
    return df

def show_info(df):
    print("SHAPE:")
    print(df.shape)

    print("\n--------")
    print("INFO:")
    df.info()

    print("\n--------")
    print("SAMPLE:")
    display(df.head())

    print("\n--------")
    print("MISSING VALUES:")
    missing = pd.DataFrame({
        'count': df.isnull().sum(),
        'percentage': (df.isnull().mean() * 100).round(2)
    })
    display(missing[missing['count'] > 0])  # only shows columns WITH missing values

    print("\n--------")
    print("UNIQUE VALUES:")
    print(df.nunique())

    print("\n--------")
    print("STATISTICAL SUMMARY:")
    display(df.describe())

## Load data

### Population

In [4]:
df_population = load_file("fao_population_2017.csv")

SHAPE:
(234, 4)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Area    234 non-null    str
 1   Year    234 non-null    int64
 2   Unit    234 non-null    str
 3   Value   234 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 7.4 KB

--------
SAMPLE:

             Area  Year     Unit      Value
0     Afghanistan  2017  1000 No  35688.935
1         Albania  2017  1000 No   2898.242
2         Algeria  2017  1000 No  41689.299
3  American Samoa  2017  1000 No     51.586
4         Andorra  2017  1000 No     73.763

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
Area     234
Year       1
Unit       1
Value    234
dtype: int64

--------
STATISTICAL SUMMARY:

         Year         Value
count   234.0  2.340000e+02
mean   2017.0  3.883347e+04
std       0.0  1.620163e+05
min    2017.0  1.742000e+00
25%    2017.0  4.391508e+02
50%    2017.0  5.472048e+03
75%    2017.0  2.105019e+04
max    2017.0  1.444079e+06

In [5]:
df_population.Value *= 1000
df_population.drop(columns=['Unit', 'Year'], inplace=True)
df_population.rename(columns={ 'Value': 'population' }, inplace=True)
df_population

                          Area  population
0                  Afghanistan  35688935.0
1                      Albania   2898242.0
2                      Algeria  41689299.0
3               American Samoa     51586.0
4                      Andorra     73763.0
..                         ...         ...
229  Wallis and Futuna Islands     11918.0
230             Western Sahara    512843.0
231                      Yemen  33090921.0
232                     Zambia  17441320.0
233                   Zimbabwe  14812482.0

[234 rows x 2 columns]

In [6]:
countries_to_remove = [
    'China',                      # generic aggregate
    'China, Hong Kong SAR',
    'China, Macao SAR', 
    'China, Taiwan Province of',
]

df_population = df_population[
    ~df_population['Area'].isin(countries_to_remove)
]

### Poultry supply per capita

In [7]:
df_dispo = load_file("fao_disponibility_2017.csv")

SHAPE:
(171, 5)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Area     171 non-null    str
 1   Element  171 non-null    str
 2   Item     171 non-null    str
 3   Year     171 non-null    int64
 4   Value    171 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 6.8 KB

--------
SAMPLE:

,Area,Element,Item,Year,Value
0,Afghanistan,Food supply quantity (kg/capita/yr),Poultry Meat,2017,1.79
1,Albania,Food supply quantity (kg/capita/yr),Poultry Meat,2017,11.47
2,Algeria,Food supply quantity (kg/capita/yr),Poultry Meat,2017,6.86
3,Angola,Food supply quantity (kg/capita/yr),Poultry Meat,2017,10.50
4,Antigua and Barbuda,Food supply quantity (kg/capita/yr),Poultry Meat,2017,69.28

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
Area       171
Element      1
Item         1
Year         1
Value      168
dtype: int64

--------
STATISTICAL SUMMARY:

         Year       Value
count   171.0  171.000000
mean   2017.0   21.431228
std       0.0   16.742454
min    2017.0    0.620000
25%    2017.0    7.635000
50%    2017.0   18.810000
75%    2017.0   31.660000
max    2017.0   80.340000

In [8]:
df_dispo.drop(columns=['Year', 'Item', 'Element'], inplace=True)
df_dispo.rename(columns={ 'Value': 'poultry_supply_capita' }, inplace=True)

### Domestic supply

In [9]:
df_domestic = load_file("fao_domestic_supply_2017.csv")

SHAPE:
(171, 6)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Area     171 non-null    str
 1   Element  171 non-null    str
 2   Item     171 non-null    str
 3   Year     171 non-null    int64
 4   Unit     171 non-null    str
 5   Value    171 non-null    int64
dtypes: int64(2), str(4)
memory usage: 8.1 KB

--------
SAMPLE:

,Area,Element,Item,Year,Unit,Value
0,Afghanistan,Domestic supply quantity,Poultry Meat,2017,1000 t,64
1,Albania,Domestic supply quantity,Poultry Meat,2017,1000 t,33
2,Algeria,Domestic supply quantity,Poultry Meat,2017,1000 t,286
3,Angola,Domestic supply quantity,Poultry Meat,2017,1000 t,318
4,Antigua and Barbuda,Domestic supply quantity,Poultry Meat,2017,1000 t,7

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
Area       171
Element      1
Item         1
Year         1
Unit         1
Value      136
dtype: int64

--------
STATISTICAL SUMMARY:

         Year         Value
count   171.0    171.000000
mean   2017.0    781.625731
std       0.0   2555.264255
min    2017.0      2.000000
25%    2017.0     32.000000
50%    2017.0    112.000000
75%    2017.0    347.500000
max    2017.0  18670.000000

In [10]:
df_domestic.Value *= 1000000
df_domestic.drop(columns=['Year', 'Item', 'Element', 'Unit'], inplace=True)
df_domestic.rename(columns={ 'Value': 'poultry_domestic_supply' }, inplace=True)

### Chicken import

In [11]:
df_import = load_file("fao_chicken_imports_2017.csv")

SHAPE:
(194, 4)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Area    194 non-null    str
 1   Year    194 non-null    int64
 2   Unit    194 non-null    str
 3   Value   194 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 6.2 KB

--------
SAMPLE:

                  Area  Year Unit      Value
0          Afghanistan  2017    t   28937.00
1              Albania  2017    t   17515.47
2              Algeria  2017    t       0.40
3               Angola  2017    t  265888.30
4  Antigua and Barbuda  2017    t    6143.69

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
Area     194
Year       1
Unit       1
Value    194
dtype: int64

--------
STATISTICAL SUMMARY:

         Year         Value
count   194.0  1.940000e+02
mean   2017.0  6.944749e+04
std       0.0  1.628836e+05
min    2017.0  3.000000e-02
25%    2017.0  2.088358e+03
50%    2017.0  1.126037e+04
75%    2017.0  5.096881e+04
max    2017.0  1.362583e+06

In [12]:
df_import.Value *= 1000
df_import.drop(columns=['Year', 'Unit'], inplace=True)
df_import.rename(columns={ 'Value': 'poultry_import' }, inplace=True)
df_import

                                   Area  poultry_import
0                           Afghanistan      28937000.0
1                               Albania      17515470.0
2                               Algeria           400.0
3                                Angola     265888300.0
4                   Antigua and Barbuda       6143690.0
..                                  ...             ...
189  Venezuela (Bolivarian Republic of)      23121080.0
190                            Viet Nam     105695060.0
191                               Yemen      81697390.0
192                              Zambia      12010620.0
193                            Zimbabwe       5876560.0

[194 rows x 2 columns]

### Chicken production

In [13]:
df_production = load_file("fao_chicken_production_2017.csv")

SHAPE:
(195, 4)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Area    195 non-null    str
 1   Year    195 non-null    int64
 2   Unit    195 non-null    str
 3   Value   195 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 6.2 KB

--------
SAMPLE:

                  Area  Year Unit      Value
0          Afghanistan  2017    t   27637.84
1              Albania  2017    t   12912.00
2              Algeria  2017    t  364252.17
3               Angola  2017    t   40460.72
4  Antigua and Barbuda  2017    t      23.48

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
Area     195
Year       1
Unit       1
Value    195
dtype: int64

--------
STATISTICAL SUMMARY:

         Year         Value
count   195.0  1.950000e+02
mean   2017.0  6.444021e+05
std       0.0  2.218251e+06
min    2017.0  4.030000e+00
25%    2017.0  8.080025e+03
50%    2017.0  6.338300e+04
75%    2017.0  2.730770e+05
max    2017.0  1.914057e+07

In [14]:
df_production.Value *= 1000
df_production.drop(columns=['Year', 'Unit'], inplace=True)
df_production.rename(columns={ 'Value': 'poultry_production' }, inplace=True)
df_production

                                   Area  poultry_production
0                           Afghanistan          27637840.0
1                               Albania          12912000.0
2                               Algeria         364252170.0
3                                Angola          40460720.0
4                   Antigua and Barbuda             23480.0
..                                  ...                 ...
190  Venezuela (Bolivarian Republic of)         462413000.0
191                            Viet Nam         786353680.0
192                               Yemen         168628270.0
193                              Zambia          47420580.0
194                            Zimbabwe          92118470.0

[195 rows x 2 columns]

### Protein supply

In [15]:
df_protein = load_file("fao_protein_supply_2017.csv")

SHAPE:
(513, 5)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 513 entries, 0 to 512
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Area    513 non-null    str
 1   Item    513 non-null    str
 2   Year    513 non-null    int64
 3   Unit    513 non-null    str
 4   Value   513 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 20.2 KB

--------
SAMPLE:

          Area             Item  Year     Unit   Value
0  Afghanistan      Grand Total  2017  g/cap/d   65.33
1  Afghanistan  Animal Products  2017  g/cap/d   11.76
2  Afghanistan     Poultry Meat  2017  g/cap/d    0.81
3      Albania      Grand Total  2017  g/cap/d  116.34
4      Albania  Animal Products  2017  g/cap/d   64.40

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
Area     171
Item       3
Year       1
Unit       1
Value    503
dtype: int64

--------
STATISTICAL SUMMARY:

         Year       Value
count   513.0  513.000000
mean   2017.0   46.620468
std       0.0   37.246282
min    2017.0    0.280000
25%    2017.0   11.750000
50%    2017.0   41.500000
75%    2017.0   75.700000
max    2017.0  152.540000

In [16]:
df_protein.drop(columns=['Year'], inplace=True)
df_protein = df_protein.pivot_table(
    index='Area',
    columns='Item',
    values='Value',
    aggfunc='first'
).reset_index()

df_protein.rename(columns={ 
    'Animal Products': 'protein_animal_pct', 
    'Grand Total': 'protein_total_pct', 
    'Poultry Meat': 'protein_poultry_pct' 
}, inplace=True)

df_protein

Item,Area,protein_animal_pct,protein_total_pct,protein_poultry_pct
0,Afghanistan,11.76,65.33,0.81
1,Albania,64.40,116.34,5.24
2,Algeria,28.59,91.18,3.13
3,Angola,17.80,52.91,4.76
4,Antigua and Barbuda,65.14,95.42,31.50
...,...,...,...,...
166,Venezuela (Bolivarian Republic of),26.59,58.38,7.17
167,Viet Nam,32.66,88.83,4.36
168,Yemen,9.88,49.03,3.44
169,Zambia,14.52,52.20,1.56
170,Zimbabwe,26.52,57.78,2.29

### GDP

In [17]:
df_gdp = load_file("wb_gdp_per_capita_2017.csv")

SHAPE:
(266, 3)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  266 non-null    str
 1   Country Code  266 non-null    str
 2   2017          247 non-null    float64
dtypes: float64(1), str(2)
memory usage: 6.4 KB

--------
SAMPLE:

                  Country Name Country Code          2017
0                        Aruba          ABW  37524.914920
1  Africa Eastern and Southern          AFE   3837.726375
2                  Afghanistan          AFG   2335.795862
3   Africa Western and Central          AFW   5026.648499
4                       Angola          AGO   8006.836615

--------
MISSING VALUES:

      count  percentage
2017     19        7.14

--------
UNIQUE VALUES:
Country Name    266
Country Code    266
2017            245
dtype: int64

--------
STATISTICAL SUMMARY:

                2017
count     247.000000
mean    21061.842300
std     21223.503487
min       791.393495
25%      5110.512257
50%     13640.200642
75%     30133.818477
max    120774.963081

In [18]:
df_gdp.dropna(subset=['2017'], inplace=True)
df_gdp.rename(columns={ 'Country Name': 'Area', '2017': 'GDP' }, inplace=True)
df_gdp.drop(columns=['Country Code'], inplace=True)
df_gdp

                            Area           GDP
0                          Aruba  37524.914920
1    Africa Eastern and Southern   3837.726375
2                    Afghanistan   2335.795862
3     Africa Western and Central   5026.648499
4                         Angola   8006.836615
..                           ...           ...
260                        Samoa   6280.215005
261                       Kosovo   9380.940073
263                 South Africa  13738.438585
264                       Zambia   3391.627685
265                     Zimbabwe  10756.445442

[247 rows x 2 columns]

In [19]:
df_gdp[df_gdp.Area.str.contains("China")]

                     Area            GDP
40                  China   15022.437188
96   Hong Kong SAR, China   59260.913176
146      Macao SAR, China  120774.963081

### Stability

In [20]:
df_stability = load_file("wb_stability_2017.csv")

SHAPE:
(218, 3)

--------
INFO:
<class 'pandas.DataFrame'>
Index: 218 entries, 0 to 220
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   218 non-null    str
 1   Country Code   216 non-null    str
 2   2017 [YR2017]  212 non-null    float64
dtypes: float64(1), str(2)
memory usage: 6.8 KB

--------
SAMPLE:

     Country Name Country Code  2017 [YR2017]
0     Afghanistan          AFG      -2.613931
1         Albania          ALB       0.163830
2         Algeria          DZA      -0.929505
3  American Samoa          ASM       1.255594
4         Andorra          AND       1.325091

--------
MISSING VALUES:

               count  percentage
Country Code       2        0.92
2017 [YR2017]      6        2.75

--------
UNIQUE VALUES:
Country Name     218
Country Code     216
2017 [YR2017]    205
dtype: int64

--------
STATISTICAL SUMMARY:

       2017 [YR2017]
count     212.000000
mean       -0.008892
std         0.967650
min        -2.730503
25%        -0.614937
50%         0.068356
75%         0.812654
max         1.752922

In [21]:
df_stability.dropna(subset=['2017 [YR2017]'], inplace=True)
df_stability.rename(columns={ 'Country Name': 'Area', '2017 [YR2017]': 'stability' }, inplace=True)
df_stability.drop(columns=['Country Code'], inplace=True)
df_stability.info()

<class 'pandas.DataFrame'>
Index: 212 entries, 0 to 215
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Area       212 non-null    str
 1   stability  212 non-null    float64
dtypes: float64(1), str(1)
memory usage: 5.0 KB

### Urbanisation

In [22]:
df_urban = load_file("wb_urbanization_2017.csv")

SHAPE:
(265, 3)

--------
INFO:
<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_AREA_LABEL   265 non-null    str
 1   INDICATOR_LABEL  265 non-null    str
 2   2017             265 non-null    float64
dtypes: float64(1), str(2)
memory usage: 6.3 KB

--------
SAMPLE:

,REF_AREA_LABEL,INDICATOR_LABEL,2017
0,Panama,Urban population (% of total population),65.657771
1,Denmark,Urban population (% of total population),88.016194
2,IDA only,Urban population (% of total population),33.526683
3,Liechtenstein,Urban population (% of total population),14.514433
4,Eastern & Southern Africa,Urban population (% of total population),35.282987

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
REF_AREA_LABEL     265
INDICATOR_LABEL      1
2017               252
dtype: int64

--------
STATISTICAL SUMMARY:

             2017
count  265.000000
mean    59.813848
std     22.596913
min     13.524964
25%     41.710668
50%     59.953127
75%     77.912627
max    100.000000

In [23]:
df_urban.rename(columns={ 'REF_AREA_LABEL': 'Area', '2017': 'urban' }, inplace=True)
df_urban.drop(columns=['INDICATOR_LABEL'], inplace=True)
df_urban

                                   Area      urban
0                                Panama  65.657771
1                               Denmark  88.016194
2                              IDA only  33.526683
3                         Liechtenstein  14.514433
4             Eastern & Southern Africa  35.282987
..                                  ...        ...
260                                Togo  40.580946
261                             Germany  80.984254
262                           Mauritius  39.449935
263  Europe & Central Asia (IDA & IBRD)  68.367200
264                Syrian Arab Republic  74.539560

[265 rows x 2 columns]

## Merge

### Mapping

In [24]:
# Apply mapping to World Bank tables BEFORE merging
wb_country_mapping = {
    'United States': 'United States of America',
    'United Kingdom': 'United Kingdom of Great Britain and Northern Ireland',
    'China': 'China, mainland',
    'Korea, Rep.': 'Republic of Korea',
    'Turkey': 'Türkiye',
    'Vietnam': 'Viet Nam',
    'Iran, Islamic Rep.': 'Iran (Islamic Republic of)',
    'Bolivia': 'Bolivia (Plurinational State of)',
    'Venezuela, RB': 'Venezuela (Bolivarian Republic of)',
    'Congo, Dem. Rep.': 'Democratic Republic of the Congo',
    'Congo, Rep.': 'Congo',
    "Cote d'Ivoire": "Côte d'Ivoire",
    'Tanzania': 'United Republic of Tanzania',
    'Moldova': 'Republic of Moldova',
    'Lao PDR': "Lao People's Democratic Republic",
    'Netherlands': 'Netherlands (Kingdom of the)',
    'Korea, Dem. Rep.': "Democratic People's Republic of Korea",
    'Egypt, Arab Rep.': 'Egypt',
    'Yemen, Rep.': 'Yemen',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Slovak Republic': 'Slovakia',
    'Bahamas, The': 'Bahamas',
    'Gambia, The': 'Gambia',
    'Turkiye': 'Türkiye',
    'Venezuela, RB': 'Venezuela (Bolivarian Republic of)',
    'Yemen, Rep.': 'Yemen',
}

# Apply to all World Bank dataframes
df_gdp['Area'] = df_gdp['Area'].replace(wb_country_mapping)
df_urban['Area'] = df_urban['Area'].replace(wb_country_mapping)
df_stability['Area'] = df_stability['Area'].replace(wb_country_mapping)

### Join

In [25]:
df_master = df_population.copy()

df_master = df_master.merge(df_domestic, how='left', on='Area')
df_master = df_master.merge(df_dispo, how='left', on='Area')
df_master = df_master.merge(df_import, how='left', on='Area')
df_master = df_master.merge(df_production, how='left', on='Area')
df_master = df_master.merge(df_protein, how='left', on='Area')
df_master = df_master.merge(df_gdp, how='left', on='Area')
df_master = df_master.merge(df_stability, how='left', on='Area')
df_master = df_master.merge(df_urban, how='left', on='Area')

In [26]:
df_master.dropna(inplace=True)
show_info(df_master)

SHAPE:
(149, 12)

--------
INFO:
<class 'pandas.DataFrame'>
Index: 149 entries, 0 to 229
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Area                     149 non-null    str
 1   population               149 non-null    float64
 2   poultry_domestic_supply  149 non-null    float64
 3   poultry_supply_capita    149 non-null    float64
 4   poultry_import           149 non-null    float64
 5   poultry_production       149 non-null    float64
 6   protein_animal_pct       149 non-null    float64
 7   protein_total_pct        149 non-null    float64
 8   protein_poultry_pct      149 non-null    float64
 9   GDP                      149 non-null    float64
 10  stability                149 non-null    float64
 11  urban                    149 non-null    float64
dtypes: float64(11), str(1)
memory usage: 15.1 KB

--------
SAMPLE:

,Area,population,poultry_domestic_supply,poultry_supply_capita,poultry_import,poultry_production,protein_animal_pct,protein_total_pct,protein_poultry_pct,GDP,stability,urban
0,Afghanistan,35688935.0,64000000.0,1.79,28937000.0,27637840.0,11.76,65.33,0.81,2335.795862,-2.613931,24.835282
1,Albania,2898242.0,33000000.0,11.47,17515470.0,12912000.0,64.40,116.34,5.24,14110.683242,0.163830,55.980276
2,Algeria,41689299.0,286000000.0,6.86,400.0,364252170.0,28.59,91.18,3.13,13493.560749,-0.929505,71.322791
5,Angola,30234839.0,318000000.0,10.50,265888300.0,40460720.0,17.80,52.91,4.76,8006.836615,-0.537214,65.085053
7,Antigua and Barbuda,90468.0,7000000.0,69.28,6143690.0,23480.0,65.14,95.42,31.50,21422.002158,0.614623,24.850026

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
Area                       149
population                 149
poultry_domestic_supply    121
poultry_supply_capita      146
poultry_import             149
poultry_production         149
protein_animal_pct         148
protein_total_pct          147
protein_poultry_pct        144
GDP                        149
stability                  149
urban                      149
dtype: int64

--------
STATISTICAL SUMMARY:

,population,poultry_domestic_supply,poultry_supply_capita,poultry_import,poultry_production,protein_animal_pct,protein_total_pct,protein_poultry_pct,GDP,stability,urban
count,1.490000e+02,1.490000e+02,149.000000,1.490000e+02,1.490000e+02,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000
mean,4.781040e+07,7.475436e+08,20.368389,6.511917e+07,7.147507e+08,41.681812,87.594497,9.276376,20209.440621,-0.105231,58.744319
std,1.647757e+08,2.297129e+09,15.197898,1.308253e+08,2.268006e+09,21.757289,21.879051,6.931949,19242.657554,0.859713,21.304031
min,9.046800e+04,2.000000e+06,0.620000,3.000000e+01,2.348000e+04,3.660000,29.600000,0.280000,990.545051,-2.613931,13.524964
25%,2.914963e+06,3.400000e+07,7.220000,2.752280e+06,1.530000e+07,24.090000,71.000000,3.260000,5353.066088,-0.653347,42.448601
50%,9.968510e+06,1.160000e+08,18.800000,1.330698e+07,9.094400e+07,41.130000,89.800000,8.510000,13718.937867,-0.056395,60.240269
75%,3.544639e+07,3.750000e+08,28.370000,5.291815e+07,4.360400e+08,59.530000,105.430000,12.920000,28681.681559,0.629429,74.539560
max,1.412355e+09,1.830500e+10,73.010000,7.884518e+08,1.914057e+10,114.300000,152.540000,33.160000,114985.842236,1.271542,100.000000

### Check population coverage

In [27]:
world_pop = 7_550_000_000  # 2017 world population

coverage = df_master['population'].sum() / world_pop * 100
print(f"Population coverage: {coverage:.1f}%")

Population coverage: 94.4%

## Feature Engineering

In [28]:
df_master.head()

,Area,population,poultry_domestic_supply,poultry_supply_capita,poultry_import,poultry_production,protein_animal_pct,protein_total_pct,protein_poultry_pct,GDP,stability,urban
0,Afghanistan,35688935.0,64000000.0,1.79,28937000.0,27637840.0,11.76,65.33,0.81,2335.795862,-2.613931,24.835282
1,Albania,2898242.0,33000000.0,11.47,17515470.0,12912000.0,64.40,116.34,5.24,14110.683242,0.163830,55.980276
2,Algeria,41689299.0,286000000.0,6.86,400.0,364252170.0,28.59,91.18,3.13,13493.560749,-0.929505,71.322791
5,Angola,30234839.0,318000000.0,10.50,265888300.0,40460720.0,17.80,52.91,4.76,8006.836615,-0.537214,65.085053
7,Antigua and Barbuda,90468.0,7000000.0,69.28,6143690.0,23480.0,65.14,95.42,31.50,21422.002158,0.614623,24.850026

### 1. Protein ratio (%)

In [29]:
df_master['animal_protein_ratio'] = df_master['protein_animal_pct'] / df_master['protein_total_pct'] * 100
df_master['poultry_protein_ratio'] = df_master['protein_poultry_pct'] / df_master['protein_animal_pct'] * 100

### 2. Production per capita

In [30]:
df_master['production_per_capita'] = df_master['poultry_production'] / df_master.population

### 3. Gap of consumption and production

In [31]:
df_master['poultry_gap'] = df_master.poultry_supply_capita - df_master.production_per_capita

### 4. Import dependency

In [32]:
df_master['import_dependency'] = df_master.poultry_import / df_master.poultry_domestic_supply * 100

### Clean up

In [33]:
df_master.drop(columns=[
    'protein_animal_pct',
    'protein_total_pct', 
    'protein_poultry_pct',
    'poultry_domestic_supply'
], inplace=True)

df_master.rename(columns={ 'Area': 'country' }, inplace=True)

In [34]:
show_info(df_master)

SHAPE:
(149, 13)

--------
INFO:
<class 'pandas.DataFrame'>
Index: 149 entries, 0 to 229
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   country                149 non-null    str
 1   population             149 non-null    float64
 2   poultry_supply_capita  149 non-null    float64
 3   poultry_import         149 non-null    float64
 4   poultry_production     149 non-null    float64
 5   GDP                    149 non-null    float64
 6   stability              149 non-null    float64
 7   urban                  149 non-null    float64
 8   animal_protein_ratio   149 non-null    float64
 9   poultry_protein_ratio  149 non-null    float64
 10  production_per_capita  149 non-null    float64
 11  poultry_gap            149 non-null    float64
 12  import_dependency      149 non-null    float64
dtypes: float64(12), str(1)
memory usage: 16.3 KB

--------
SAMPLE:

,country,population,poultry_supply_capita,poultry_import,poultry_production,GDP,stability,urban,animal_protein_ratio,poultry_protein_ratio,production_per_capita,poultry_gap,import_dependency
0,Afghanistan,35688935.0,1.79,28937000.0,27637840.0,2335.795862,-2.613931,24.835282,18.000918,6.887755,0.774409,1.015591,45.214063
1,Albania,2898242.0,11.47,17515470.0,12912000.0,14110.683242,0.163830,55.980276,55.354994,8.136646,4.455115,7.014885,53.077182
2,Algeria,41689299.0,6.86,400.0,364252170.0,13493.560749,-0.929505,71.322791,31.355560,10.947884,8.737306,-1.877306,0.000140
5,Angola,30234839.0,10.50,265888300.0,40460720.0,8006.836615,-0.537214,65.085053,33.642034,26.741573,1.338215,9.161785,83.612673
7,Antigua and Barbuda,90468.0,69.28,6143690.0,23480.0,21422.002158,0.614623,24.850026,68.266611,48.357384,0.259539,69.020461,87.767000

--------
MISSING VALUES:

Empty DataFrame
Columns: [count, percentage]
Index: []

--------
UNIQUE VALUES:
country                  149
population               149
poultry_supply_capita    146
poultry_import           149
poultry_production       149
GDP                      149
stability                149
urban                    149
animal_protein_ratio     149
poultry_protein_ratio    149
production_per_capita    149
poultry_gap              149
import_dependency        149
dtype: int64

--------
STATISTICAL SUMMARY:

,population,poultry_supply_capita,poultry_import,poultry_production,GDP,stability,urban,animal_protein_ratio,poultry_protein_ratio,production_per_capita,poultry_gap,import_dependency
count,1.490000e+02,149.000000,1.490000e+02,1.490000e+02,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000
mean,4.781040e+07,20.368389,6.511917e+07,7.147507e+08,20209.440621,-0.105231,58.744319,44.742236,21.880913,16.220160,4.148230,31.068718
std,1.647757e+08,15.197898,1.308253e+08,2.268006e+09,19242.657554,0.859713,21.304031,15.506058,12.931268,15.965379,13.051673,33.740108
min,9.046800e+04,0.620000,3.000000e+01,2.348000e+04,990.545051,-2.613931,13.524964,7.910801,1.698571,0.070868,-43.944155,0.000001
25%,2.914963e+06,7.220000,2.752280e+06,1.530000e+07,5353.066088,-0.653347,42.448601,32.312704,11.136537,2.208664,0.005816,3.308647
50%,9.968510e+06,18.800000,1.330698e+07,9.094400e+07,13718.937867,-0.056395,60.240269,46.538187,19.402776,12.019215,1.999012,17.692390
75%,3.544639e+07,28.370000,5.291815e+07,4.360400e+08,28681.681559,0.629429,74.539560,56.570991,32.439199,26.026625,7.548653,58.192876
max,1.412355e+09,73.010000,7.884518e+08,1.914057e+10,114985.842236,1.271542,100.000000,74.931166,53.755102,66.473489,71.068370,135.127064

## Export

In [35]:
# df_master.to_csv(Path() / "data" / "clean" / 'master_2017.csv', index=False)