In [ ]:
# library
import pandas as pd

In [ ]:
# import file

df = pd.read_excel(
        'data_insee.xlsx',
        sheet_name="2022",
        header=None
    )
df.head()

(28, 64)

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,"Estimation de population au 1er janvier, par r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Année 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Régions,Ensemble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,0 à 4 ans,5 à 9 ans,10 à 14 ans,15 à 19 ans,20 à 24 ans,25 à 29 ans,30 à 34 ans,35 à 39 ans,40 à 44 ans,...,55 à 59 ans,60 à 64 ans,65 à 69 ans,70 à 74 ans,75 à 79 ans,80 à 84 ans,85 à 89 ans,90 à 94 ans,95 ans et plus,Total
5,Auvergne-Rhône-Alpes,434649,492463,515533,502055,467786,457651,500268,520284,518637,...,266994,249936,239136,232996,169044,126248,103462,58895,21595,4185266

In [ ]:
# get age groups

age_groups = df.iloc[4, 5:21].tolist()
print(age_groups)
print(len(age_groups))

['20 à 24 ans', '25 à 29 ans', '30 à 34 ans', '35 à 39 ans', '40 à 44 ans', '45 à 49 ans', '50 à 54 ans', '55 à 59 ans', '60 à 64 ans', '65 à 69 ans', '70 à 74 ans', '75 à 79 ans', '80 à 84 ans', '85 à 89 ans', '90 à 94 ans', '95 ans et plus']
16

In [ ]:
# get regions

regions = df.iloc[5:18, 0].tolist()
print(regions)
print(len(regions))

print(df.iloc[24, 0])

['Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Bretagne', 'Centre-Val-de-Loire', 'Corse', 'Grand Est', 'Hauts-de-France', 'Île-de-France', 'Normandie', 'Nouvelle-Aquitaine', 'Occitanie', 'Pays de la Loire', "Provence-Alpes-Côte d'Azur"]
13
DOM

In [ ]:
# find start and end points(columns) of age groups for 2 genders

print("Male age groups:")
print(df.iloc[5, 26])  # start
print(df.iloc[5, 41])  # end = start + 15

print("Female age groups:")
print(df.iloc[5, 47])
print(df.iloc[5, 62])

Male age groups:
239255
5394
Female age groups:
228531
21595

In [ ]:
# retreive all data from 2022

all_data = []

regions_rows = range(5, 18)  # rows 5 to 17

for r_idx in regions_rows:
    region = df.iloc[r_idx, 0]
    row = df.iloc[r_idx]
    
    # Loop over age groups
    for ag_idx, age_group in enumerate(age_groups):
        pop_m = row.iloc[26 + ag_idx]
        pop_f = row.iloc[47 + ag_idx]
        
        # Add one row for M, one row for F
        all_data.append({'REGION': region, 'AGE_GROUP': age_group, 'GENDER': 'M', 'POPULATION': pop_m})
        all_data.append({'REGION': region, 'AGE_GROUP': age_group, 'GENDER': 'F', 'POPULATION': pop_f})

result = pd.DataFrame(all_data)
print(result.head(10))

                 REGION    AGE_GROUP GENDER  POPULATION
0  Auvergne-Rhône-Alpes  20 à 24 ans      M      239255
1  Auvergne-Rhône-Alpes  20 à 24 ans      F      228531
2  Auvergne-Rhône-Alpes  25 à 29 ans      M      229782
3  Auvergne-Rhône-Alpes  25 à 29 ans      F      227869
4  Auvergne-Rhône-Alpes  30 à 34 ans      M      247295
5  Auvergne-Rhône-Alpes  30 à 34 ans      F      252973
6  Auvergne-Rhône-Alpes  35 à 39 ans      M      254980
7  Auvergne-Rhône-Alpes  35 à 39 ans      F      265304
8  Auvergne-Rhône-Alpes  40 à 44 ans      M      255076
9  Auvergne-Rhône-Alpes  40 à 44 ans      F      263561

In [ ]:
# retreive all data from 4 years

years = [2022, 2023, 2024, 2025]
all_data = []
regions_rows = range(5, 19)  # originally (5, 18), for adding DOM, put 19
age_groups = df.iloc[4, 5:21].tolist()
regions = df.iloc[5:18, 0].tolist().append(df.iloc[24, 0])  # plus DOM

for year in years:
    df = pd.read_excel(
        "data_insee.xlsx",
        sheet_name=str(year),
        header=None
    )
    
    for r_index in regions_rows:
        region = df.iloc[r_index, 0] if r_index < 18 else 'DOM'
        row = df.iloc[r_index] if r_index < 18 else df.iloc[24]

        for index, age in enumerate(age_groups):
            pop_m = row.iloc[26 + index]
            pop_f = row.iloc[47 + index]

            all_data.append(
                {
                    "YEAR": year,
                    "REGION": region,
                    "AGE_GROUP": age,
                    "GENDER": "M",
                    "POPULATION": pop_m
                }
            )
            all_data.append(
                {
                    "YEAR": year,
                    "REGION": region,
                    "AGE_GROUP": age,
                    "GENDER": "F",
                    "POPULATION": pop_f
                }
            )

result = pd.DataFrame(all_data)
result.head()

   YEAR                REGION    AGE_GROUP GENDER  POPULATION
0  2022  Auvergne-Rhône-Alpes  20 à 24 ans      M      239255
1  2022  Auvergne-Rhône-Alpes  20 à 24 ans      F      228531
2  2022  Auvergne-Rhône-Alpes  25 à 29 ans      M      229782
3  2022  Auvergne-Rhône-Alpes  25 à 29 ans      F      227869
4  2022  Auvergne-Rhône-Alpes  30 à 34 ans      M      247295

In [ ]:
# prepare age group mapping

age_oc = ['20-24 ans',
'25-29 ans',
'30-34 ans',
'35-39 ans',
'40-44 ans',
'45-49 ans',
'50-54 ans',
'55-59 ans',
'60 ans ou plus']

print(len(age_oc))

9

In [ ]:
# mapping age groups

age_mapping = dict()

for index, group in enumerate(age_groups):
    index_oc = index if index < 9 else 8
    age_mapping[group] = age_oc[index_oc]

In [ ]:
# apply into dataframe

result["AGE_GROUP"] = result["AGE_GROUP"].map(age_mapping)

# as_index means reset_index()
result = result.groupby(["YEAR", "REGION", "AGE_GROUP", "GENDER"], as_index=False)["POPULATION"].sum()

In [ ]:
# match region name

result['REGION'] = result['REGION'].replace('DOM', 'DROM')

In [ ]:
# Export csv

result.to_csv(
    "insee_population.csv",
    index=False,
    encoding='utf-8'
)